#!/usr/bin/env bash

# basic installs
sudo apt update && sudo apt upgrade -y
sudo apt install build-essential curl dirmngr libssl-dev libreadline-dev zlib1g-dev -y

# install git
sudo add-apt-repository -y ppa:git-core/ppa
sudo apt update
sudo apt install git -y

# install keybase
curl -O https://prerelease.keybase.io/keybase_amd64.deb
## if you see an error about missing `libappindicator1`
## from the next command, you can ignore it, as the
## subsequent command corrects it
sudo dpkg -i keybase_amd64.deb
sudo apt-get install -f
run_keybase
rm keybase_amd64.deb

# create folders
mkdir -p ~/.local/bin
mkdir ~/src

# asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.3
. ~/.asdf/asdf.sh

# node
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
. ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
asdf install nodejs 11.7.0
asdf global nodejs 11.7.0

# ruby
asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
asdf install ruby 2.6.0
asdf global ruby 2.6.0

# keychain
cd ~/src
wget -O keychain-2.8.5.tar.gz https://github.com/funtoo/keychain/archive/2.8.5.tar.gz
tar xzvf keychain-2.8.5.tar.gz
cd keychain-2.8.5/
make clean && make
cp keychain ~/.local/bin/

# decrypt yadm files and setup alt links
printf "\nDecrypting YADM files...\n"
yadm decrypt
yadm alt

# set yadm git committer
yadm gitconfig user.name "mrajo"
yadm gitconfig user.email "anthony.c@stle.co"

